doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            App\Shared\Infrastructure\Orm\UuidType: App\Shared\Infrastructure\Orm\UuidType
            App\Shared\Infrastructure\Orm\DateTimeType: App\Shared\Infrastructure\Orm\DateTimeType
            App\Reservation\Infrastructure\Orm\ReservationGuestsType: App\Reservation\Infrastructure\Orm\ReservationGuestsType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Hotel:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Hotel/Infrastructure/Orm'
                prefix: 'App\Hotel\Domain'
                alias: Hotel
            HotelProviderRelation:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Hotel/Infrastructure/Orm'
                prefix: 'App\Hotel\Domain'
                alias: HotelProviderRelation
            Reservation:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Reservation/Infrastructure/Orm'
                prefix: 'App\Reservation\Domain'
                alias: Reservation
        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
