Homepage:
    path: /
    controller: App\Shared\Infrastructure\Api\HomepageController

Health:
    prefix: /api/v1
    resource: ../src/Health/Infrastructure/Api/routes.yaml
    trailing_slash_on_root: false

Reservation:
    prefix: /api/v1
    resource: ../src/Reservation/Infrastructure/Api/routes.yaml
    trailing_slash_on_root: false
