version: "3"

services:
    db:
        image: postgres:16.2
        restart: always
        ports:
            - "${DB_PORT}:${DB_PORT}"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_HOST: ${DB_HOST}
            POSTGRES_PORT: ${DB_PORT}
        container_name: reservation-db
        volumes:
            - db_app:/var/lib/postgresql/data
        networks:
            - reservation_api
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/html:cached
        networks:
            - reservation_api
        depends_on:
            - db
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/html:cached
        ports:
            - 80:80
        networks:
            - reservation_api
        env_file:
            - .env.nginx.local

volumes:
    db_app:

networks:
    reservation_api: